spring.application.name=supermercado

# H2 en memoria — sin instalación
spring.datasource.url=jdbc:h2:mem:vetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Consola H2 en http://localhost:8080/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false

# JWT
jwt.secret=clave-super-secreta-para-jwt-proyecto-vet-2024-frameworks

server.port=8080
